name: Build Insecure Original CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3        

      - name: Build an image from Dockerfile
        run: docker build ./insecure-original/node-app -t node-app-insecure:v1         

      - name: Run Trivy vulnerability scanner against code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './insecure-original/node-app'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy vulnerability scanner against image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'node-app-insecure:v1'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'