name: Build Insecure Original CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3        

      - name: Build an image from Dockerfile
        run: docker build ./insecure-original/node-app -t node-app-insecure:v1         