name: Build Securely Modified CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test            

      - name: Run Trivy vulnerability scanner against code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './insecure-original/node-app'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'        

      - name: Build an image from Dockerfile
        run: docker build ./securely-modified/node-app -t node-app-secure:v1 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'node-app-secure:v1'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'          